server:
  servlet:
    context-path: /wakishop/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wakishop
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update